[package]
name = "banana"
version = "0.1.0"
authors = ["simon"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.45"
console_error_panic_hook = "0.1.6"
rand = { version = "0.7", features = ["wasm-bindgen"] }
