[package]
name = "fire"
version = "0.1.0"
authors = ["simon"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.45"
#rand = "0.6.5"
js-sys = "0.3.22"
console_error_panic_hook = "0.1.6"
